### ISSUE TITLE
The 0.7.2 build does not correspond to the real 0.7.2 code version

### ISSUE THREAD

**Issue by parfeniukink** [tomasvotava/fastapi-sso#93]
I found that you do imports in `fastapi_sso.__init__.py`

But actually, this build from PyPi does not have those changes:

![Alacritty 2023-11-23](https://github.com/tomasvotava/fastapi-sso/assets/45270625/f2377005-b23a-4783-8627-3e568f73a706)

👉 After I made a build by myself I found that it worked exactly how I expected.

![Alacritty 2023-11-23](https://github.com/tomasvotava/fastapi-sso/assets/45270625/64d08944-2ff6-45cc-af97-7825f2ef2d05)

Could you please publish the correct version to the Pypi?

**Comment by tomasvotava** [comment]
Oh darn, thank you so much @parfeniukink! The 0.7.2 tag actually does not have those imports yet, I've just been really busy these last couple of weeks and didn't make a new release yet. 

https://github.com/tomasvotava/fastapi-sso/blob/0.7.2/fastapi_sso/__init__.py

I'll create a 0.7.3 now, I'll try to setup a pipeline so that releases are published automatically, so that my laziness does not affect this project this much 🙄

**Comment by tomasvotava** [comment]
`0.7.3` released https://github.com/tomasvotava/fastapi-sso/releases/tag/0.7.3
Thanks again!

**Comment by parfeniukink** [comment]
> `0.7.3` released https://github.com/tomasvotava/fastapi-sso/releases/tag/0.7.3 Thanks again!

Nice! Really halpful!
Whait for some PRs :)
